FROM ubuntu
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
 	git

# 	openssh-client \
# 	libgomp1

#libgomp1 is required by lightgbm

#	build-essential \
#	gcc \

ENTRYPOINT ["ls"]
CMD []
